server:
  port: 8080
  servlet:
    context-path: /
upload:
  dir: /home/username/uploads
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/dental_clinic_management"
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "tuan6a1thcstv@gmail.com"
    password: "iiwx melq vdwy ilrl"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations: classpath:/static/, file:src/main/resources/static/img/
logging:
  level:
    org:
      springframework:
        security: DEBUG
file:
  upload-dir: src/main/resources/static/assets/image/